version: 0.2

env:
  variables:
    PAKETO_BUILDER_VERSION: 0.2.326-full
    LIFECYCLE_VERSION: 0.16.0

phases:
  pre_build:
    commands:
      - codebuild-breakpoint

  build:
    commands:
      - /work/build.sh
