version: 2
jobs:
    build:
        machine:
            image: ubuntu-1604:202004-01

        steps:
            - checkout

            - run:
                name: build containers
                command: cp .circleci/env .env && make build

            - run:
                name: run black (code formatting check)
                command: make docker_black

            - run:
                name: run flake8 (coding standards compliance test)
                command: make docker_flake8

            - run:
                name: Output CSS files
                command: make compilescss

            - run:
                name: run tests
                command: ./run-tests.sh
