# Generated by Django 2.2.13 on 2020-09-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200907_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='on_behalf_of',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
