# Generated by Django 2.2.13 on 2020-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_booking_on_behalf_of"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="desk",
        ),
        migrations.RemoveField(
            model_name="floor",
            name="desks",
        ),
        migrations.AddField(
            model_name="floor",
            name="nr_of_desks",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
