# Generated by Django 2.2.16 on 2020-09-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200908_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
