# Generated by Django 3.1.1 on 2020-11-03 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0012_directorate_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="PRA",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("authorized_reason", models.CharField(max_length=80)),
                ("group", models.CharField(blank=True, max_length=80, null=True)),
                ("business_unit", models.CharField(blank=True, max_length=80, null=True)),
                ("risk_category", models.CharField(max_length=80)),
                ("mitigation_outcome", models.CharField(blank=True, default="", max_length=40)),
                ("mitigation_measures", models.TextField(blank=True, default="")),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("approved_staff_member", models.BooleanField(null=True)),
                ("approved_scs", models.BooleanField(null=True)),
                (
                    "line_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pra_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
