# Generated by Django 3.1.4 on 2020-12-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_pra_migrated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pra",
            options={
                "verbose_name": "Personal Risk Assessment",
                "verbose_name_plural": "Personal Risk Assessments",
            },
        ),
    ]
